// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQVklpWmkI6j92NpY4pLilfSV1EdNmZY',
    appId: '1:519830977024:web:a27874621f021f72ac76e5',
    messagingSenderId: '519830977024',
    projectId: 'kidst-aa673',
    authDomain: 'kidst-aa673.firebaseapp.com',
    storageBucket: 'kidst-aa673.firebasestorage.app',
    measurementId: 'G-GVJ6MV7KJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9EaeiPL6fuVToTT8Xei9SEpfrVloIimU',
    appId: '1:519830977024:android:9abd05b3f11bfb31ac76e5',
    messagingSenderId: '519830977024',
    projectId: 'kidst-aa673',
    storageBucket: 'kidst-aa673.firebasestorage.app',
  );
}
